// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured yet.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS is not configured yet.');
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not configured yet.');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not configured yet.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported.');
      case TargetPlatform.fuchsia:
        throw UnsupportedError('Fuchsia is not supported.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzKmNngh-fIyrZOf1iWKp-rvBcixLhHfo',
    appId: '1:509693229826:android:b19e14e5cb6afbd9dda01b',
    messagingSenderId: '509693229826',
    projectId: 'scanpos-703e6',
    storageBucket: 'scanpos-703e6.firebasestorage.app',
  );
}